import mongoose from "mongoose";
import { User } from "../models/user.model.js";
import { Product } from "../models/product.model.js";
import { TrackingDevice } from "../models/tracking-device.model.js";
import { TrackingEvent } from "../models/tracking-event.model.js";
import { DeviceHealth } from "../models/device-health.model.js";
import { PrivacyAlert } from "../models/privacy-alert.model.js";
import { Notification } from "../models/notification.model.js";
import { AIInsight } from "../models/ai-insight.model.js";
import { FamilyMember } from "../models/family-member.model.js";
import { connectDB } from "../config/db.js";

async function seed() {
  await connectDB();

  console.log("\n🧹 Clearing existing data...");
  await Promise.all([
    User.deleteMany({}),
    Product.deleteMany({}),
    TrackingDevice.deleteMany({}),
    TrackingEvent.deleteMany({}),
    DeviceHealth.deleteMany({}),
    PrivacyAlert.deleteMany({}),
    Notification.deleteMany({}),
    AIInsight.deleteMany({}),
    FamilyMember.deleteMany({}),
  ]);

  // ── 1. Users ──
  console.log("👤 Creating users...");
  await User.create({
    name: "Ananya Sharma",
    email: "admin@tagx.com",
    password: "Admin@123",
    role: "admin",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya",
      publicId: "avatars/admin",
    },
    preferences: {
      theme: "dark",
      notifications: true,
      emailAlerts: true,
      smsAlerts: false,
      language: "en",
      timezone: "Asia/Kolkata",
      privacyScanEnabled: true,
    },
    lastLogin: new Date(),
  });

  const demo = await User.create({
    name: "Rahul Kapoor",
    email: "demo@tagx.com",
    password: "Demo@123",
    role: "user",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul",
      publicId: "avatars/demo",
    },
    preferences: {
      theme: "dark",
      notifications: true,
      emailAlerts: true,
      smsAlerts: false,
      language: "en",
      timezone: "Asia/Kolkata",
      privacyScanEnabled: true,
    },
    lastLogin: new Date(),
  });

  // ── 2. Products ──
  console.log("🏷️  Creating products...");
  const products = await Product.insertMany([
    {
      name: "TagX Pro",
      slug: "tagx-pro",
      description:
        "Our flagship Bluetooth tracker with 100m range, IP67 waterproofing, and a 1-year battery. The most advanced tag for everyday carry. Built with precision engineering and a robust companion app, the TagX Pro ensures you never lose sight of what matters.",
      shortDescription: "Premium tracker with 100m range & 1-year battery.",
      price: 2999,
      compareAtPrice: 3499,
      sku: "TGX-PRO-001",
      images: [
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-pro", publicId: "tagx/tagx-pro", alt: "TagX Pro front view", isPrimary: true },
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-pro-back", publicId: "tagx/tagx-pro-back", alt: "TagX Pro back view", isPrimary: false },
      ],
      category: "personal",
      tags: ["premium", "waterproof", "long-range", "best-seller"],
      features: [
        "100m Bluetooth range",
        "IP67 Waterproof",
        "1 Year battery life",
        "Built-in speaker",
        "Crowd GPS network",
      ],
      specs: {
        battery: "1 year (CR2032)",
        range: "100m (328ft)",
        waterproof: "IP67",
        weight: "12g",
        dimensions: "32 × 32 × 6 mm",
        connectivity: "Bluetooth 5.3",
      },
      isFeatured: true,
      seo: {
        metaTitle: "TagX Pro - Premium Bluetooth Tracker | TagX",
        metaDescription: "TagX Pro is our flagship Bluetooth tracker with 100m range, IP67 waterproofing, and 1-year battery life. Never lose your belongings again.",
        keywords: ["bluetooth tracker", "tagx pro", "item finder", "waterproof tracker"],
      },
    },
    {
      name: "TagX Mini",
      slug: "tagx-mini",
      description:
        "Ultra-compact tracker designed for wallets and small items. Only 6mm thin — slides into any card slot unnoticed. Perfect for your wallet, passport case, or any tight space where every millimeter counts.",
      shortDescription: "Ultra-slim tracker for wallets & cards.",
      price: 1999,
      sku: "TGX-MINI-002",
      images: [
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-mini", publicId: "tagx/tagx-mini", alt: "TagX Mini next to credit card", isPrimary: true },
      ],
      category: "personal",
      tags: ["slim", "wallet", "compact", "card-slot"],
      features: [
        "6mm ultra-slim design",
        "60m Bluetooth range",
        "6 Month battery",
        "Card-slot fit",
        "Water resistant",
      ],
      specs: {
        battery: "6 months (CR1220)",
        range: "60m (197ft)",
        waterproof: "IP54",
        weight: "6g",
        dimensions: "40 × 25 × 6 mm",
        connectivity: "Bluetooth 5.2",
      },
      isFeatured: true,
      seo: {
        metaTitle: "TagX Mini - Ultra-Slim Wallet Tracker | TagX",
        metaDescription: "TagX Mini is an ultra-compact 6mm thin tracker designed for wallets and cards. Slides into any card slot unnoticed.",
        keywords: ["wallet tracker", "slim tracker", "card tracker", "tagx mini"],
      },
    },
    {
      name: "TagX Pet",
      slug: "tagx-pet",
      description:
        "Built for dogs and cats. Collar-mountable with a rugged shell, 150m range, and activity monitoring for your furry friend. With temperature alerts and activity tracking, you'll always know your pet is safe.",
      shortDescription: "Rugged tracker for pets with 150m range.",
      price: 3499,
      compareAtPrice: 3999,
      sku: "TGX-PET-003",
      images: [
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-pet", publicId: "tagx/tagx-pet", alt: "TagX Pet on dog collar", isPrimary: true },
      ],
      category: "pet",
      tags: ["pet", "dog", "cat", "collar", "waterproof"],
      features: [
        "150m Bluetooth range",
        "IP68 Waterproof",
        "Collar mount included",
        "Activity monitoring",
        "Temperature alerts",
        "6 Month battery",
      ],
      specs: {
        battery: "6 months (rechargeable)",
        range: "150m (492ft)",
        waterproof: "IP68",
        weight: "24g",
        dimensions: "45 × 35 × 12 mm",
        connectivity: "Bluetooth 5.3",
      },
      isFeatured: true,
      seo: {
        metaTitle: "TagX Pet - Waterproof Pet Tracker | TagX",
        metaDescription: "TagX Pet is a rugged, waterproof Bluetooth tracker for dogs and cats with 150m range, activity monitoring, and temperature alerts.",
        keywords: ["pet tracker", "dog tracker", "cat tracker", "collar tracker"],
      },
    },
    {
      name: "TagX Vehicle",
      slug: "tagx-vehicle",
      description:
        "GPS-assisted tracker for vehicles. Hide it in your car, bike, or scooter and get instant alerts if it moves without you. Heat-resistant design ensures reliable performance even under the hood.",
      shortDescription: "GPS + Bluetooth tracker for vehicles.",
      price: 4999,
      sku: "TGX-VHL-004",
      images: [
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-vehicle", publicId: "tagx/tagx-vehicle", alt: "TagX Vehicle mounted in car", isPrimary: true },
      ],
      category: "vehicle",
      tags: ["vehicle", "car", "bike", "gps", "anti-theft"],
      features: [
        "GPS + Bluetooth hybrid",
        "Motion detection alerts",
        "Heat resistant up to 80°C",
        "Magnetic mount",
        "1 Year battery",
      ],
      specs: {
        battery: "1 year (lithium)",
        range: "200m (656ft)",
        waterproof: "IP65",
        weight: "32g",
        dimensions: "50 × 30 × 15 mm",
        connectivity: "Bluetooth 5.3 + GPS",
      },
      isFeatured: false,
      seo: {
        metaTitle: "TagX Vehicle - GPS Vehicle Tracker | TagX",
        metaDescription: "TagX Vehicle is a GPS-assisted Bluetooth tracker for cars, bikes, and scooters with motion alerts and heat-resistant design.",
        keywords: ["vehicle tracker", "car tracker", "gps tracker", "anti-theft"],
      },
    },
    {
      name: "TagX Luggage",
      slug: "tagx-luggage",
      description:
        "Travel-ready tracker for suitcases and bags. Airlines-compatible design with global roaming support via crowd GPS. Never lose your luggage again with real-time tracking at major airports worldwide.",
      shortDescription: "Travel tracker with global crowd GPS.",
      price: 3999,
      compareAtPrice: 4499,
      sku: "TGX-LUG-005",
      images: [
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-luggage", publicId: "tagx/tagx-luggage", alt: "TagX Luggage on suitcase", isPrimary: true },
      ],
      category: "luggage",
      tags: ["travel", "luggage", "suitcase", "airport", "global"],
      features: [
        "Global crowd GPS network",
        "Airline-safe battery",
        "Bag tag slot compatible",
        "150m Bluetooth range",
        "Travel mode",
      ],
      specs: {
        battery: "9 months (CR2477)",
        range: "150m (492ft)",
        waterproof: "IP65",
        weight: "18g",
        dimensions: "38 × 38 × 8 mm",
        connectivity: "Bluetooth 5.3",
      },
      isFeatured: false,
      seo: {
        metaTitle: "TagX Luggage - Global Travel Tracker | TagX",
        metaDescription: "TagX Luggage is a travel-ready Bluetooth tracker for suitcases and bags with global crowd GPS support and airline-safe battery.",
        keywords: ["luggage tracker", "travel tracker", "bag tracker", "airport tracker"],
      },
    },
    {
      name: "TagX Kids",
      slug: "tagx-kids",
      description:
        "Safety tracker for children. Waterproof, colorful, and paired with a parent app that sends instant alerts if your child leaves a safe zone. With geofencing and an SOS button, peace of mind is just a tap away.",
      shortDescription: "Safety tracker for kids with geofencing.",
      price: 4499,
      sku: "TGX-KIDS-006",
      images: [
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-kids", publicId: "tagx/tagx-kids", alt: "TagX Kids on child's wristband", isPrimary: true },
        { url: "https://res.cloudinary.com/demo/image/upload/v1/tagx/tagx-kids-blue", publicId: "tagx/tagx-kids-blue", alt: "TagX Kids blue variant", isPrimary: false },
      ],
      category: "kids",
      tags: ["kids", "safety", "geofence", "sos", "parental"],
      features: [
        "Geofence alerts",
        "IP67 Waterproof",
        "Fun color options",
        "SOS button",
        "Safe zone setup",
        "Rechargeable battery",
      ],
      specs: {
        battery: "3 days (rechargeable)",
        range: "80m (262ft)",
        waterproof: "IP67",
        weight: "20g",
        dimensions: "40 × 30 × 10 mm",
        connectivity: "Bluetooth 5.3",
      },
      isFeatured: true,
      seo: {
        metaTitle: "TagX Kids - Child Safety Tracker | TagX",
        metaDescription: "TagX Kids is a waterproof Bluetooth tracker for children with geofencing, SOS button, and real-time parent alerts via the TagX app.",
        keywords: ["kids tracker", "child safety", "geofence tracker", "parental control"],
      },
    },
  ]);

  // ── 3. Tracking Devices ──
  console.log("📡 Creating tracking devices...");
  const devices = await TrackingDevice.insertMany([
    {
      user: demo._id,
      name: "TagX Pro",
      type: "tag",
      serialNumber: "TGX-PRO-001A",
      status: "active",
      batteryLevel: 82,
      signalStrength: 75,
      lastSeen: new Date(Date.now() - 2 * 60 * 1000),
      firmwareVersion: "2.4.1",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PRO-2024",
      temperature: 28,
      pairedAt: new Date("2025-12-01"),
      location: {
        lat: 12.9716,
        lng: 77.5946,
        address: "Orion Mall, Brigade Road, Bangalore",
        accuracy: 5,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 100,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: true,
      },
      metadata: { source: "retail", purchaseDate: new Date("2025-12-05") },
    },
    {
      user: demo._id,
      name: "iPhone 15",
      type: "phone",
      serialNumber: "TGX-PHN-002B",
      status: "active",
      batteryLevel: 34,
      signalStrength: 90,
      lastSeen: new Date(),
      firmwareVersion: "2.4.0",
      hardwareVersion: "1.1.0",
      manufacturer: "Apple",
      deviceModel: "iPhone 15 Pro",
      temperature: 32,
      pairedAt: new Date("2025-11-15"),
      location: {
        lat: 12.9344,
        lng: 77.6101,
        address: "Home, Indiranagar, Bangalore",
        accuracy: 3,
      },
      settings: {
        notifyOnLeftBehind: false,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 50,
        trackingInterval: 120,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Wallet Tag",
      type: "wallet",
      serialNumber: "TGX-WAL-003C",
      status: "idle",
      batteryLevel: 67,
      signalStrength: 45,
      lastSeen: new Date(Date.now() - 1 * 60 * 60 * 1000),
      firmwareVersion: "2.3.2",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-MINI-2024",
      temperature: 26,
      pairedAt: new Date("2026-01-10"),
      location: {
        lat: 12.9716,
        lng: 77.5946,
        address: "Orion Mall, Brigade Road, Bangalore",
        accuracy: 10,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 50,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Max (Pet)",
      type: "pet",
      serialNumber: "TGX-PET-004D",
      status: "offline",
      batteryLevel: 8,
      signalStrength: 0,
      lastSeen: new Date(Date.now() - 3 * 60 * 60 * 1000),
      firmwareVersion: "2.4.1",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PET-2024",
      temperature: 30,
      pairedAt: new Date("2026-02-20"),
      location: { lat: 0, lng: 0, address: "Unknown", accuracy: 0 },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 200,
        trackingInterval: 30,
        precisionFindingEnabled: false,
        ledIndicator: true,
      },
      metadata: { petName: "Max", species: "dog", breed: "Golden Retriever" },
    },
    {
      user: demo._id,
      name: "Car Keys",
      type: "key",
      serialNumber: "TGX-KEY-005E",
      status: "active",
      batteryLevel: 91,
      signalStrength: 80,
      lastSeen: new Date(Date.now() - 10 * 60 * 1000),
      firmwareVersion: "2.4.0",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-MINI-2024",
      temperature: 27,
      pairedAt: new Date("2026-03-01"),
      location: {
        lat: 12.9344,
        lng: 77.6101,
        address: "Home, Indiranagar, Bangalore",
        accuracy: 2,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 30,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: true,
      },
      metadata: { vehicleType: "car", vehicleModel: "Honda City" },
    },
    {
      user: demo._id,
      name: "Sony Headphones",
      type: "tag",
      serialNumber: "TGX-TAG-006F",
      status: "idle",
      batteryLevel: 45,
      signalStrength: 30,
      lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000),
      firmwareVersion: "2.3.0",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PRO-2024",
      temperature: 24,
      pairedAt: new Date("2026-01-20"),
      location: {
        lat: 12.9352,
        lng: 77.6245,
        address: "MG Road Metro Station, Bangalore",
        accuracy: 8,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: false,
        geofenceRadius: 50,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Office Bag",
      type: "wallet",
      serialNumber: "TGX-BAG-007G",
      status: "active",
      batteryLevel: 73,
      signalStrength: 65,
      lastSeen: new Date(Date.now() - 30 * 60 * 1000),
      firmwareVersion: "2.4.1",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PRO-2024",
      temperature: 26,
      pairedAt: new Date("2026-01-05"),
      location: {
        lat: 19.076,
        lng: 72.8777,
        address: "BKC, Mumbai",
        accuracy: 6,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 100,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Scooty",
      type: "key",
      serialNumber: "TGX-VHL-008H",
      status: "active",
      batteryLevel: 88,
      signalStrength: 95,
      lastSeen: new Date(Date.now() - 5 * 60 * 1000),
      firmwareVersion: "2.4.0",
      hardwareVersion: "1.1.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-VHL-2024",
      temperature: 35,
      pairedAt: new Date("2026-03-15"),
      location: {
        lat: 12.9344,
        lng: 77.6101,
        address: "Home Parking, Indiranagar, Bangalore",
        accuracy: 2,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 20,
        trackingInterval: 120,
        precisionFindingEnabled: false,
        ledIndicator: true,
      },
      metadata: { vehicleType: "scooter", vehicleModel: "TVS Jupiter" },
    },
    {
      user: demo._id,
      name: "Luggage Bag",
      type: "wallet",
      serialNumber: "TGX-LUG-009I",
      status: "offline",
      batteryLevel: 15,
      signalStrength: 0,
      lastSeen: new Date(Date.now() - 24 * 60 * 60 * 1000),
      firmwareVersion: "2.2.1",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-LUG-2024",
      temperature: 22,
      pairedAt: new Date("2026-04-01"),
      location: {
        lat: 28.6139,
        lng: 77.209,
        address: "New Delhi Railway Station",
        accuracy: 50,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 500,
        trackingInterval: 300,
        precisionFindingEnabled: false,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Rover (Pet)",
      type: "pet",
      serialNumber: "TGX-PET-010J",
      status: "low_battery",
      batteryLevel: 12,
      signalStrength: 55,
      lastSeen: new Date(Date.now() - 45 * 60 * 1000),
      firmwareVersion: "2.3.3",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PET-2024",
      temperature: 29,
      pairedAt: new Date("2026-04-10"),
      location: {
        lat: 12.9507,
        lng: 77.6427,
        address: "Cubbon Park, Bangalore",
        accuracy: 7,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 200,
        trackingInterval: 30,
        precisionFindingEnabled: false,
        ledIndicator: true,
      },
      metadata: { petName: "Rover", species: "dog", breed: "Labrador" },
    },
  ]);

  // ── 4. Tracking Events ──
  console.log("📋 Creating tracking events...");
  const now = Date.now();
  await TrackingEvent.insertMany([
    {
      device: devices[0]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "TagX Pro spotted at Orion Mall, Sector 3",
      icon: "map-pin",
      source: "bluetooth",
      location: { lat: 12.9716, lng: 77.5946, address: "Orion Mall, Bangalore" },
      metadata: {},
      timestamp: new Date(now - 2 * 60 * 1000),
    },
    {
      device: devices[1]._id,
      type: "connection",
      severity: "info",
      title: "Reconnected",
      description: "iPhone reconnected after being out of range for 12 minutes",
      icon: "bluetooth",
      source: "bluetooth",
      metadata: {},
      timestamp: new Date(now - 5 * 60 * 1000),
    },
    {
      device: devices[3]._id,
      type: "alert",
      severity: "warning",
      title: "Geofence Alert",
      description: "Max left Home zone — last seen at Cubbon Park",
      icon: "alert",
      source: "gps",
      location: { lat: 12.9507, lng: 77.6427, address: "Cubbon Park, Bangalore" },
      metadata: { petName: "Max" },
      timestamp: new Date(now - 20 * 60 * 1000),
    },
    {
      device: devices[0]._id,
      type: "status",
      severity: "info",
      title: "Firmware Updated",
      description: "TagX Pro updated to v2.4.1 successfully",
      icon: "power",
      source: "system",
      metadata: { previousVersion: "2.4.0", newVersion: "2.4.1" },
      timestamp: new Date(now - 2 * 60 * 60 * 1000),
    },
    {
      device: devices[4]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "Car Keys detected at Home parking spot",
      icon: "map-pin",
      source: "bluetooth",
      location: { lat: 12.9344, lng: 77.6101, address: "Home, Bangalore" },
      metadata: {},
      timestamp: new Date(now - 10 * 60 * 1000),
    },
    {
      device: devices[2]._id,
      type: "alert",
      severity: "warning",
      title: "Left Behind Alert",
      description: "Wallet Tag detected as left behind at Orion Mall",
      icon: "alert",
      source: "bluetooth",
      location: { lat: 12.9716, lng: 77.5946, address: "Orion Mall, Bangalore" },
      metadata: {},
      timestamp: new Date(now - 1 * 60 * 60 * 1000),
    },
    {
      device: devices[5]._id,
      type: "connection",
      severity: "info",
      title: "Disconnected",
      description: "Sony Headphones went out of range at MG Road Metro",
      icon: "wifi",
      source: "bluetooth",
      location: { lat: 12.9352, lng: 77.6245, address: "MG Road Metro, Bangalore" },
      metadata: {},
      timestamp: new Date(now - 2 * 60 * 60 * 1000),
    },
    {
      device: devices[7]._id,
      type: "status",
      severity: "warning",
      title: "Battery Low",
      description: "Scooty tag battery at 12% — consider replacing soon",
      icon: "power",
      source: "system",
      metadata: { batteryLevel: 12 },
      timestamp: new Date(now - 30 * 60 * 1000),
    },
    {
      device: devices[9]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "Rover is roaming at Cubbon Park, 500m from home",
      icon: "map-pin",
      source: "gps",
      location: { lat: 12.9507, lng: 77.6427, address: "Cubbon Park, Bangalore" },
      metadata: {},
      timestamp: new Date(now - 45 * 60 * 1000),
    },
    {
      device: devices[8]._id,
      type: "alert",
      severity: "critical",
      title: "Out of Range",
      description: "Luggage bag tag not seen since yesterday — last pinged at New Delhi Railway Station",
      icon: "alert",
      source: "crowd",
      location: { lat: 28.6139, lng: 77.209, address: "New Delhi Railway Station" },
      metadata: { hoursSinceLastSeen: 24 },
      timestamp: new Date(now - 24 * 60 * 60 * 1000),
    },
    {
      device: devices[6]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "Office Bag arrived at BKC, Mumbai",
      icon: "map-pin",
      source: "crowd",
      location: { lat: 19.076, lng: 72.8777, address: "BKC, Mumbai" },
      metadata: {},
      timestamp: new Date(now - 30 * 60 * 1000),
    },
  ]);

  // ── 5. Device Health ──
  console.log("❤️  Creating device health records...");
  await DeviceHealth.insertMany([
    { device: devices[0]._id, uptime: 99.8, signalStrength: 75, batteryHealth: 92, temperature: 28, connectionErrors: 0, firmwareVersion: "2.4.1", timestamp: new Date(now - 10 * 60 * 1000), metrics: [] },
    { device: devices[1]._id, uptime: 98.5, signalStrength: 90, batteryHealth: 78, temperature: 32, memoryUsage: 45, connectionErrors: 2, firmwareVersion: "2.4.0", timestamp: new Date(now - 5 * 60 * 1000), metrics: [] },
    { device: devices[2]._id, uptime: 95.2, signalStrength: 45, batteryHealth: 85, temperature: 26, connectionErrors: 1, firmwareVersion: "2.3.2", timestamp: new Date(now - 1 * 60 * 60 * 1000), metrics: [] },
    { device: devices[3]._id, uptime: 88.0, signalStrength: 0, batteryHealth: 22, temperature: 30, connectionErrors: 15, firmwareVersion: "2.4.1", timestamp: new Date(now - 3 * 60 * 60 * 1000), metrics: [] },
    { device: devices[4]._id, uptime: 99.9, signalStrength: 80, batteryHealth: 97, temperature: 27, connectionErrors: 0, firmwareVersion: "2.4.0", timestamp: new Date(now - 10 * 60 * 1000), metrics: [] },
    { device: devices[5]._id, uptime: 92.1, signalStrength: 30, batteryHealth: 65, temperature: 24, connectionErrors: 3, firmwareVersion: "2.3.0", timestamp: new Date(now - 2 * 60 * 60 * 1000), metrics: [] },
    { device: devices[6]._id, uptime: 97.4, signalStrength: 65, batteryHealth: 88, temperature: 26, connectionErrors: 1, firmwareVersion: "2.4.1", timestamp: new Date(now - 30 * 60 * 1000), metrics: [] },
    { device: devices[7]._id, uptime: 99.6, signalStrength: 95, batteryHealth: 94, temperature: 35, connectionErrors: 0, firmwareVersion: "2.4.0", timestamp: new Date(now - 5 * 60 * 1000), metrics: [] },
    { device: devices[8]._id, uptime: 76.3, signalStrength: 0, batteryHealth: 30, temperature: 22, connectionErrors: 22, firmwareVersion: "2.2.1", timestamp: new Date(now - 24 * 60 * 60 * 1000), metrics: [] },
    { device: devices[9]._id, uptime: 85.0, signalStrength: 55, batteryHealth: 40, temperature: 29, connectionErrors: 5, firmwareVersion: "2.3.3", timestamp: new Date(now - 45 * 60 * 1000), metrics: [] },
    { device: devices[0]._id, uptime: 99.7, signalStrength: 72, batteryHealth: 91, temperature: 27, connectionErrors: 0, firmwareVersion: "2.4.1", timestamp: new Date(now - 2 * 60 * 60 * 1000), metrics: [] },
    { device: devices[1]._id, uptime: 98.5, signalStrength: 88, batteryHealth: 77, temperature: 31, memoryUsage: 48, connectionErrors: 1, firmwareVersion: "2.4.0", timestamp: new Date(now - 1 * 60 * 60 * 1000), metrics: [] },
  ]);

  // ── 6. Privacy Alerts ──
  console.log("🛡️  Creating privacy alerts...");
  await PrivacyAlert.insertMany([
    {
      user: demo._id,
      severity: "info",
      title: "Privacy Scan Complete",
      description: "No unknown trackers detected in your vicinity. Your area is secure.",
      metadata: { scanDuration: "2.3s" },
      timestamp: new Date(now - 10 * 60 * 1000),
    },
    {
      user: demo._id,
      severity: "warning",
      title: "Unknown Tracker Detected",
      description: "An unknown Bluetooth device has been following your route for 15 minutes on MG Road.",
      location: "MG Road, Bangalore",
      coordinates: { lat: 12.9352, lng: 77.6245 },
      actionLabel: "Investigate",
      metadata: { deviceType: "BLE", signalStrength: -65 },
      timestamp: new Date(now - 30 * 60 * 1000),
    },
    {
      user: demo._id,
      severity: "critical",
      title: "Anti-Stalking Alert",
      description: "A tracker not in your network has been consistently near you for 30+ minutes at Indiranagar.",
      location: "Indiranagar, Bangalore",
      coordinates: { lat: 12.9344, lng: 77.6101 },
      actionLabel: "Scan Now",
      metadata: { proximityDuration: "32m", detections: 8 },
      timestamp: new Date(now - 45 * 60 * 1000),
    },
    {
      user: demo._id,
      severity: "info",
      title: "Safe Zone Verified",
      description: "Your Home zone is secure. No unknown devices detected in the last 24 hours.",
      metadata: { zone: "Home", safeDevices: 4 },
      timestamp: new Date(now - 2 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      severity: "warning",
      title: "AirTag Detected Nearby",
      description: "An Apple AirTag is moving with you. It may be attached to your belongings.",
      location: "Commercial Street, Bangalore",
      coordinates: { lat: 12.9823, lng: 77.6097 },
      actionLabel: "Find Device",
      metadata: { detectedVia: "iOS", manufacturer: "Apple" },
      timestamp: new Date(now - 3 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      severity: "info",
      title: "Scan Complete — All Clear",
      description: "Privacy scan completed. 12 known devices, 0 unknown devices detected.",
      metadata: { knownDevices: 12, unknownDevices: 0, scanDuration: "1.8s" },
      timestamp: new Date(now - 6 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      severity: "critical",
      title: "Tracker Found in Bag",
      description: "An unknown tracking device was detected in your vicinity for over 1 hour at Orion Mall.",
      location: "Orion Mall, Bangalore",
      coordinates: { lat: 12.9716, lng: 77.5946 },
      actionLabel: "Locate Device",
      metadata: { proximityDuration: "67m", detections: 15 },
      timestamp: new Date(now - 12 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      severity: "info",
      title: "Weekly Privacy Report",
      description: "7 scans completed this week. 2 unknown trackers detected and resolved.",
      metadata: { totalScans: 7, threatsFound: 2, threatsResolved: 2 },
      timestamp: new Date(now - 24 * 60 * 60 * 1000),
    },
  ]);

  // ── 7. Notifications ──
  console.log("🔔 Creating notifications...");
  await Notification.insertMany([
    {
      user: demo._id,
      type: "location",
      priority: "high",
      title: "TagX Pro Found",
      description: "Located at Orion Mall, Sector 3 — within your safe zone.",
      actionable: true,
      category: "device_location",
      metadata: { deviceId: devices[0]._id.toString() },
      timestamp: new Date(now - 2 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "security",
      priority: "normal",
      title: "New Device Paired",
      description: "AirPods Pro added to your network. Encryption enabled.",
      read: true,
      readAt: new Date(now - 14 * 60 * 1000),
      category: "device_pairing",
      metadata: {},
      timestamp: new Date(now - 15 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "insight",
      priority: "low",
      title: "Weekly Report Ready",
      description: "You saved 23 minutes this week by not searching for lost items.",
      read: true,
      readAt: new Date(now - 55 * 60 * 1000),
      category: "weekly_report",
      metadata: { timeSaved: 23, unit: "minutes" },
      timestamp: new Date(now - 1 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "reminder",
      priority: "normal",
      title: "Battery Reminder",
      description: "Wallet Tag battery is below 20%. Consider replacing the battery soon.",
      actionable: true,
      actionLabel: "Order Battery",
      category: "battery",
      metadata: { deviceId: devices[2]._id.toString(), batteryLevel: 15 },
      timestamp: new Date(now - 3 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "location",
      priority: "low",
      title: "Car Keys Located",
      description: "Your Car Keys are at Home parking spot.",
      read: true,
      readAt: new Date(now - 8 * 60 * 1000),
      category: "device_location",
      metadata: { deviceId: devices[4]._id.toString() },
      timestamp: new Date(now - 10 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "security",
      priority: "normal",
      title: "Privacy Scan Reminder",
      description: "You haven't run a privacy scan today. Stay safe!",
      actionable: true,
      actionLabel: "Scan Now",
      category: "privacy",
      metadata: {},
      timestamp: new Date(now - 5 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "insight",
      priority: "low",
      title: "Pattern Detected",
      description: "You tend to leave your keys in the living room between 6-8 PM.",
      category: "behavior",
      metadata: {},
      timestamp: new Date(now - 6 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "reminder",
      priority: "low",
      title: "Firmware Update Available",
      description: "New firmware v2.5.0 available for TagX Pet.",
      actionable: true,
      actionLabel: "Update Now",
      actionUrl: "app://firmware",
      category: "firmware",
      metadata: { deviceId: devices[3]._id.toString(), version: "2.5.0" },
      timestamp: new Date(now - 12 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "location",
      priority: "high",
      title: "Geofence Alert",
      description: "TagX Pet Rover has left the Home safe zone.",
      actionable: true,
      category: "geofence",
      metadata: { deviceId: devices[9]._id.toString(), zone: "Home" },
      timestamp: new Date(now - 45 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "insight",
      priority: "low",
      title: "Battery Forecast",
      description: "TagX Pet battery predicted to last 12 more days at current usage.",
      category: "battery",
      metadata: { deviceId: devices[3]._id.toString(), daysRemaining: 12 },
      timestamp: new Date(now - 2 * 60 * 60 * 1000),
    },
  ]);

  // ── 8. AI Insights ──
  console.log("🤖 Creating AI insights...");
  await AIInsight.insertMany([
    {
      user: demo._id,
      type: "insight",
      category: "usage",
      title: "Pattern Detected",
      description: "You tend to leave your keys in the living room between 6-8 PM. Check the couch.",
      confidence: 0.87,
      actionable: true,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 5 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "prediction",
      category: "battery",
      title: "Battery Forecast",
      description: "TagX Pet battery predicted to last 12 more days based on current usage patterns.",
      confidence: 0.94,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 1 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "alert",
      category: "location",
      title: "Unusual Activity",
      description: "Wallet Tag moved outside your usual zone during work hours. Possible misplacement.",
      actionable: true,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 30 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "suggestion",
      category: "general",
      title: "Optimize Placement",
      description: "Moving your TagX Pro closer to the entrance improves signal strength by 40%.",
      confidence: 0.78,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 2 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "prediction",
      category: "usage",
      title: "Forgetting Pattern",
      description: "Based on your history, there's an 82% chance you'll forget your wallet on Friday evenings.",
      confidence: 0.82,
      actionable: true,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 4 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "insight",
      category: "usage",
      title: "Recovery Stats",
      description: "You've saved 47 minutes this week using TagX — that's 34% faster than last week.",
      confidence: 0.95,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 8 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "suggestion",
      category: "security",
      title: "Family Sharing Suggestion",
      description: "Add family members to your network to get notified when they enter safe zones.",
      confidence: 0.72,
      actionable: true,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 12 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "alert",
      category: "location",
      title: "Signal Degradation",
      description: "Your TagX Pro signal has been weakening. Check for Bluetooth interference.",
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 18 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "prediction",
      category: "usage",
      title: "Travel Prediction",
      description: "You usually pack your Luggage Tag on Friday mornings. Don't forget it for your trip!",
      confidence: 0.88,
      actionable: true,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 24 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "insight",
      category: "usage",
      title: "Most Used Feature",
      description: "You use location tracking 73% more than any other feature. Precision Finding is your favorite.",
      confidence: 0.91,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 48 * 60 * 60 * 1000),
    },
    {
      user: demo._id,
      type: "alert",
      category: "location",
      title: "Max Location Outdated",
      description: "TagX Pet Max hasn't reported location in 3 hours. Last seen at Cubbon Park.",
      actionable: true,
      modelName: "groq/llama-3.3-70b",
      metadata: {},
      timestamp: new Date(now - 3 * 60 * 60 * 1000),
    },
  ]);

  // ── 9. Family Members ──
  console.log("👨‍👩‍👧‍👦 Creating family members...");
  await FamilyMember.insertMany([
    {
      owner: demo._id,
      user: demo._id,
      name: "Rahul Kapoor",
      email: "demo@tagx.com",
      role: "Owner",
      relationship: "self",
      devices: 10,
      status: "active",
      location: "Home, Bangalore",
      isOwner: true,
      permissions: ["track_location", "view_devices", "receive_alerts", "manage_members", "view_insights"],
      joinedAt: new Date("2025-12-01"),
    },
    {
      owner: demo._id,
      name: "Priya Kapoor",
      email: "priya.kapoor@email.com",
      phone: "+91-9876543210",
      role: "Partner",
      relationship: "wife",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
      devices: 2,
      status: "active",
      location: "Work, MG Road",
      permissions: ["track_location", "view_devices", "receive_alerts", "view_insights"],
      invitedAt: new Date("2026-01-15"),
      joinedAt: new Date("2026-01-20"),
    },
    {
      owner: demo._id,
      name: "Arjun Kapoor",
      email: "arjun.k@school.edu",
      role: "Child",
      relationship: "son",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun",
      devices: 1,
      status: "active",
      location: "School, Indiranagar",
      permissions: ["track_location", "receive_alerts"],
      invitedAt: new Date("2026-02-01"),
      joinedAt: new Date("2026-02-05"),
    },
    {
      owner: demo._id,
      name: "Mr. Kapoor",
      email: "raj.kapoor@email.com",
      role: "Parent",
      relationship: "father",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MrKapoor",
      devices: 3,
      status: "idle",
      location: "Home, Delhi",
      permissions: ["view_devices", "receive_alerts"],
      invitedAt: new Date("2026-03-01"),
    },
    {
      owner: demo._id,
      name: "Mrs. Kapoor",
      email: "sarita.kapoor@email.com",
      role: "Parent",
      relationship: "mother",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MrsKapoor",
      devices: 2,
      status: "offline",
      location: "Unknown",
      permissions: ["view_devices"],
      invitedAt: new Date("2026-03-01"),
    },
    {
      owner: demo._id,
      name: "Neha Kapoor",
      email: "neha.k@college.edu",
      role: "Sibling",
      relationship: "sister",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Neha",
      devices: 1,
      status: "active",
      location: "College, Koramangala",
      permissions: ["track_location", "view_devices", "receive_alerts"],
      invitedAt: new Date("2026-04-01"),
      joinedAt: new Date("2026-04-05"),
    },
  ]);

  console.log("\n✅ Seed complete!");
  console.log(`   👤 ${2} users (admin + demo)`);
  console.log(`   🏷️  ${products.length} products`);
  console.log(`   📡 ${devices.length} tracking devices`);
  console.log(`   📋 ${11} tracking events`);
  console.log(`   ❤️  ${12} device health records`);
  console.log(`   🛡️  ${8} privacy alerts`);
  console.log(`   🔔 ${10} notifications`);
  console.log(`   🤖 ${11} AI insights`);
  console.log(`   👨‍👩‍👧‍👦 ${6} family members\n`);

  console.log("   Demo login:  demo@tagx.com / Demo@123");
  console.log("   Admin login: admin@tagx.com / Admin@123\n");

  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
