import mongoose from "mongoose";
import { User } from "../models/user.model.js";
import { Product } from "../models/product.model.js";
import { TrackingDevice } from "../models/tracking-device.model.js";
import { TrackingEvent } from "../models/tracking-event.model.js";
import { DeviceHealth } from "../models/device-health.model.js";
import { PrivacyAlert } from "../models/privacy-alert.model.js";
import { Notification } from "../models/notification.model.js";
import { AIInsight } from "../models/ai-insight.model.js";
import { FamilyMember } from "../models/family-member.model.js";
import { connectDB } from "../config/db.js";
import { generateText } from "../services/groq.service.js";

async function batchGenerate(items: { prompt: string; fallback: string }[], concurrency = 5) {
  const results: string[] = [];
  for (let i = 0; i < items.length; i += concurrency) {
    const batch = items.slice(i, i + concurrency);
    const batchResults = await Promise.all(batch.map((item) => generateText(item.prompt, item.fallback)));
    results.push(...batchResults);
  }
  return results;
}

async function seed() {
  await connectDB();

  console.log("\n🧹 Clearing existing data...");
  await Promise.all([
    User.deleteMany({}),
    Product.deleteMany({}),
    TrackingDevice.deleteMany({}),
    TrackingEvent.deleteMany({}),
    DeviceHealth.deleteMany({}),
    PrivacyAlert.deleteMany({}),
    Notification.deleteMany({}),
    AIInsight.deleteMany({}),
    FamilyMember.deleteMany({}),
  ]);

  // ── 1. Users ──
  console.log("👤 Creating users...");
  await User.create({
    name: "Ananya Sharma",
    email: "admin@tagx.com",
    password: "Admin@123",
    role: "admin",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya",
      publicId: "avatars/admin",
    },
    preferences: {
      theme: "dark",
      notifications: true,
      emailAlerts: true,
      smsAlerts: false,
      language: "en",
      timezone: "Asia/Kolkata",
      privacyScanEnabled: true,
    },
    lastLogin: new Date(),
  });

  const demo = await User.create({
    name: "Rahul Kapoor",
    email: "demo@tagx.com",
    password: "Demo@123",
    role: "user",
    isVerified: true,
    avatar: {
      url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul",
      publicId: "avatars/demo",
    },
    preferences: {
      theme: "dark",
      notifications: true,
      emailAlerts: true,
      smsAlerts: false,
      language: "en",
      timezone: "Asia/Kolkata",
      privacyScanEnabled: true,
    },
    lastLogin: new Date(),
  });

  // ── 2. Products ──
  console.log("🏷️  Creating products...");
  const products = await Product.insertMany([

    // ── B2C Products (₹1,999 – ₹2,999) ──
    {
      name: "TagX Pro",
      slug: "tagx-pro",
      description: "Our flagship Bluetooth tracker with 100m range, IP67 waterproofing, and a 1-year battery. The most advanced tag for everyday carry. Built with precision engineering and a robust companion app, the TagX Pro ensures you never lose sight of what matters.",
      shortDescription: "Premium tracker with 100m range & 1-year battery.",
      price: 2499,
      compareAtPrice: 2999,
      costPrice: 1200,
      sku: "TGX-PRO-B2C-001",
      images: [
        { url: "/TagX Pro.png", publicId: "tagx-pro", alt: "TagX Pro front view", isPrimary: true },
      ],
      category: "personal",
      tags: ["premium", "waterproof", "long-range", "best-seller", "b2c"],
      features: ["100m Bluetooth range", "IP67 Waterproof", "1 Year battery life", "Built-in speaker", "Crowd GPS network"],
      specs: { battery: "1 year (CR2032)", range: "100m (328ft)", waterproof: "IP67", weight: "12g", dimensions: "32 × 32 × 6 mm", connectivity: "Bluetooth 5.3" },
      isFeatured: true,
      seo: { metaTitle: "TagX Pro – Premium Bluetooth Tracker | TagX", metaDescription: "TagX Pro is our flagship Bluetooth tracker with 100m range, IP67 waterproofing, and 1-year battery life.", keywords: ["bluetooth tracker", "tagx pro", "item finder", "waterproof tracker"] },
    },
    {
      name: "TagX Mini",
      slug: "tagx-mini",
      description: "Ultra-compact tracker designed for wallets and small items. Only 6mm thin — slides into any card slot unnoticed. Perfect for your wallet, passport case, or any tight space where every millimeter counts.",
      shortDescription: "Ultra-slim tracker for wallets & cards.",
      price: 1999,
      costPrice: 900,
      sku: "TGX-MINI-B2C-002",
      images: [
        { url: "/TagX Mini.png", publicId: "tagx-mini", alt: "TagX Mini next to credit card", isPrimary: true },
      ],
      category: "personal",
      tags: ["slim", "wallet", "compact", "card-slot", "b2c"],
      features: ["6mm ultra-slim design", "60m Bluetooth range", "6 Month battery", "Card-slot fit", "Water resistant"],
      specs: { battery: "6 months (CR1220)", range: "60m (197ft)", waterproof: "IP54", weight: "6g", dimensions: "40 × 25 × 6 mm", connectivity: "Bluetooth 5.2" },
      isFeatured: true,
      seo: { metaTitle: "TagX Mini – Ultra-Slim Wallet Tracker | TagX", metaDescription: "TagX Mini is an ultra-compact 6mm thin tracker for wallets and cards.", keywords: ["wallet tracker", "slim tracker", "card tracker", "tagx mini"] },
    },
    {
      name: "TagX Pet",
      slug: "tagx-pet",
      description: "Built for dogs and cats. Collar-mountable with a rugged shell, 150m range, and activity monitoring for your furry friend. With temperature alerts and activity tracking, you'll always know your pet is safe.",
      shortDescription: "Rugged tracker for pets with 150m range.",
      price: 2999,
      compareAtPrice: 3499,
      costPrice: 1400,
      sku: "TGX-PET-B2C-003",
      images: [
        { url: "/TagX Pet.png", publicId: "tagx-pet", alt: "TagX Pet on dog collar", isPrimary: true },
      ],
      category: "pet",
      tags: ["pet", "dog", "cat", "collar", "waterproof", "b2c"],
      features: ["150m Bluetooth range", "IP68 Waterproof", "Collar mount included", "Activity monitoring", "Temperature alerts", "6 Month battery"],
      specs: { battery: "6 months (rechargeable)", range: "150m (492ft)", waterproof: "IP68", weight: "24g", dimensions: "45 × 35 × 12 mm", connectivity: "Bluetooth 5.3" },
      isFeatured: true,
      seo: { metaTitle: "TagX Pet – Waterproof Pet Tracker | TagX", metaDescription: "TagX Pet is a rugged, waterproof Bluetooth tracker for dogs and cats.", keywords: ["pet tracker", "dog tracker", "cat tracker", "collar tracker"] },
    },
    {
      name: "TagX Vehicle",
      slug: "tagx-vehicle",
      description: "GPS-assisted tracker for vehicles. Hide it in your car, bike, or scooter and get instant alerts if it moves without you. Heat-resistant design ensures reliable performance even under the hood.",
      shortDescription: "GPS + Bluetooth tracker for vehicles.",
      price: 2499,
      costPrice: 1300,
      sku: "TGX-VHL-B2C-004",
      images: [
        { url: "/Tagx Bike.png", publicId: "tagx-vehicle", alt: "TagX Vehicle mounted in car", isPrimary: true },
      ],
      category: "vehicle",
      tags: ["vehicle", "car", "bike", "gps", "anti-theft", "b2c"],
      features: ["GPS + Bluetooth hybrid", "Motion detection alerts", "Heat resistant up to 80°C", "Magnetic mount", "1 Year battery"],
      specs: { battery: "1 year (lithium)", range: "200m (656ft)", waterproof: "IP65", weight: "32g", dimensions: "50 × 30 × 15 mm", connectivity: "Bluetooth 5.3 + GPS" },
      isFeatured: false,
      seo: { metaTitle: "TagX Vehicle – GPS Vehicle Tracker | TagX", metaDescription: "TagX Vehicle is a GPS-assisted Bluetooth tracker for cars, bikes, and scooters.", keywords: ["vehicle tracker", "car tracker", "gps tracker", "anti-theft"] },
    },
    {
      name: "TagX Luggage",
      slug: "tagx-luggage",
      description: "Travel-ready tracker for suitcases and bags. Airlines-compatible design with global roaming support via crowd GPS. Never lose your luggage again with real-time tracking at major airports worldwide.",
      shortDescription: "Travel tracker with global crowd GPS.",
      price: 2299,
      compareAtPrice: 2799,
      costPrice: 1000,
      sku: "TGX-LUG-B2C-005",
      images: [
        { url: "/TagX Luggage.png", publicId: "tagx-luggage", alt: "TagX Luggage on suitcase", isPrimary: true },
      ],
      category: "luggage",
      tags: ["travel", "luggage", "suitcase", "airport", "global", "b2c"],
      features: ["Global crowd GPS network", "Airline-safe battery", "Bag tag slot compatible", "150m Bluetooth range", "Travel mode"],
      specs: { battery: "9 months (CR2477)", range: "150m (492ft)", waterproof: "IP65", weight: "18g", dimensions: "38 × 38 × 8 mm", connectivity: "Bluetooth 5.3" },
      isFeatured: false,
      seo: { metaTitle: "TagX Luggage – Global Travel Tracker | TagX", metaDescription: "TagX Luggage is a travel-ready Bluetooth tracker with global crowd GPS.", keywords: ["luggage tracker", "travel tracker", "bag tracker", "airport tracker"] },
    },
    {
      name: "TagX Kids",
      slug: "tagx-kids",
      description: "Safety tracker for children. Waterproof, colorful, and paired with a parent app that sends instant alerts if your child leaves a safe zone. With geofencing and an SOS button, peace of mind is just a tap away.",
      shortDescription: "Safety tracker for kids with geofencing.",
      price: 2999,
      costPrice: 1500,
      sku: "TGX-KIDS-B2C-006",
      images: [
        { url: "/TagX Kids.png", publicId: "tagx-kids", alt: "TagX Kids on child's wristband", isPrimary: true },
      ],
      category: "kids",
      tags: ["kids", "safety", "geofence", "sos", "parental", "b2c"],
      features: ["Geofence alerts", "IP67 Waterproof", "Fun color options", "SOS button", "Safe zone setup", "Rechargeable battery"],
      specs: { battery: "3 days (rechargeable)", range: "80m (262ft)", waterproof: "IP67", weight: "20g", dimensions: "40 × 30 × 10 mm", connectivity: "Bluetooth 5.3" },
      isFeatured: true,
      seo: { metaTitle: "TagX Kids – Child Safety Tracker | TagX", metaDescription: "TagX Kids is a waterproof Bluetooth tracker for children with geofencing and SOS button.", keywords: ["kids tracker", "child safety", "geofence tracker", "parental control"] },
    },
    {
      name: "TagX Wallet Card",
      slug: "tagx-wallet-card",
      description: "Credit-card shaped tracker that sits in your wallet alongside your cards. Only 2mm thick with a 2-year battery — set it and forget it.",
      shortDescription: "Card-shaped tracker for your wallet.",
      price: 2499,
      costPrice: 1100,
      sku: "TGX-WALLET-B2C-007",
      images: [
        { url: "/TagX Mini.png", publicId: "tagx-wallet", alt: "TagX Wallet Card next to credit cards", isPrimary: true },
      ],
      category: "personal",
      tags: ["wallet", "card", "slim", "long-battery", "b2c"],
      features: ["Credit-card size (2mm thin)", "2 Year battery life", "80m Bluetooth range", "Passive crowd GPS", "Water splash resistant"],
      specs: { battery: "2 years (CR2032)", range: "80m (262ft)", waterproof: "IP52", weight: "8g", dimensions: "54 × 36 × 2 mm", connectivity: "Bluetooth 5.3" },
      isFeatured: true,
      seo: { metaTitle: "TagX Wallet Card – Smart Wallet Tracker | TagX", metaDescription: "TagX Wallet Card is a credit-card shaped tracker that fits in your wallet with a 2-year battery.", keywords: ["wallet tracker", "card tracker", "slim tracker", "tagx wallet"] },
    },

    // ── B2B / Enterprise Products (volume & API pricing, based on B2C) ──
    {
      name: "TagX Enterprise Hub",
      slug: "tagx-enterprise-hub",
      description: "Central gateway for managing up to 200 TagX devices across your business. Includes real-time dashboard, employee access control, API keys, and dedicated support. The foundation for any TagX fleet deployment.",
      shortDescription: "Central gateway for managing up to 200 devices.",
      price: 14999,
      costPrice: 7000,
      sku: "TGX-ENT-HUB-001",
      images: [
        { url: "/TagX Pro.png", publicId: "tagx-enterprise-hub", alt: "TagX Enterprise Hub device", isPrimary: true },
      ],
      category: "enterprise",
      tags: ["enterprise", "gateway", "fleet-management", "api", "b2b"],
      features: ["Manage up to 200 devices", "Real-time fleet dashboard", "API access (REST + WebSocket)", "Employee role management", "Dedicated account manager", "99.9% SLA uptime"],
      specs: { battery: "Powered (USB-C)", range: "N/A (gateway)", waterproof: "IP42", weight: "120g", dimensions: "100 × 70 × 25 mm", connectivity: "Wi-Fi + Ethernet + Bluetooth 5.3" },
      isFeatured: true,
      seo: { metaTitle: "TagX Enterprise Hub – Fleet Management Gateway | TagX", metaDescription: "TagX Enterprise Hub manages up to 200 TagX devices with real-time dashboards, API access, and dedicated support.", keywords: ["enterprise tracker", "fleet management", "asset tracking", "b2b tracker"] },
    },
    {
      name: "TagX Pro – Fleet Pack (10-pack)",
      slug: "tagx-pro-fleet-pack",
      description: "Bulk pack of 10 TagX Pro units with enterprise mounting hardware and shared management console. Ideal for retail inventory, warehouse asset tracking, or office equipment. Includes priority support.",
      shortDescription: "10× TagX Pro units + fleet console.",
      price: 19999,
      compareAtPrice: 24990,
      costPrice: 10000,
      sku: "TGX-PRO-B2B-010",
      images: [
        { url: "/TagX Pro.png", publicId: "tagx-pro-10pack", alt: "TagX Pro 10-pack box", isPrimary: true },
      ],
      category: "enterprise",
      tags: ["enterprise", "bulk", "fleet", "warehouse", "b2b", "best-seller"],
      features: ["10× TagX Pro units (₹1,999/unit)", "Enterprise mounting kit", "Shared fleet console", "Priority customer support", "Extended 2-year warranty", "Bulk provisioning via NFC"],
      specs: { battery: "1 year each (CR2032)", range: "100m (328ft)", waterproof: "IP67", weight: "12g each", dimensions: "Each: 32 × 32 × 6 mm", connectivity: "Bluetooth 5.3" },
      isFeatured: true,
      seo: { metaTitle: "TagX Pro Fleet Pack – 10-Pack Enterprise | TagX", metaDescription: "TagX Pro Fleet Pack includes 10 units with enterprise console, priority support, and extended warranty.", keywords: ["fleet pack", "bulk tracker", "enterprise tracker", "10-pack"] },
    },
    {
      name: "TagX Vehicle – Fleet Bundle (5-pack)",
      slug: "tagx-vehicle-fleet-bundle",
      description: "Five TagX Vehicle trackers with GPS+Bluetooth hybrid, plus fleet dashboard and geofence management. Perfect for delivery fleets, logistics companies, and car rental businesses.",
      shortDescription: "5× Vehicle trackers + fleet dashboard.",
      price: 9999,
      compareAtPrice: 12495,
      costPrice: 5500,
      sku: "TGX-VHL-B2B-005",
      images: [
        { url: "/Tagx Bike.png", publicId: "tagx-vehicle-5pack", alt: "TagX Vehicle 5-pack", isPrimary: true },
      ],
      category: "enterprise",
      tags: ["enterprise", "fleet", "vehicle", "logistics", "b2b", "gps"],
      features: ["5× Vehicle trackers (₹1,999/unit)", "GPS + Bluetooth hybrid", "Geofence zone management", "Fleet movement dashboard", "Heat-resistant mount kit", "Bulk provisioning"],
      specs: { battery: "1 year each (lithium)", range: "200m (656ft)", waterproof: "IP65", weight: "32g each", dimensions: "Each: 50 × 30 × 15 mm", connectivity: "Bluetooth 5.3 + GPS" },
      isFeatured: false,
      seo: { metaTitle: "TagX Vehicle Fleet Bundle – 5-Pack | TagX", metaDescription: "TagX Vehicle Fleet Bundle includes 5 GPS-assisted trackers with fleet dashboard for logistics and delivery businesses.", keywords: ["fleet tracking", "vehicle fleet", "logistics tracker", "gps fleet"] },
    },
    {
      name: "TagX Asset Tracking API – Annual",
      slug: "tagx-asset-api-annual",
      description: "Full REST + WebSocket API access to the TagX tracking network. Integrate real-time location data into your own apps, dashboards, or ERP. Includes 50,000 API calls/month and dedicated support.",
      shortDescription: "API access for custom integrations.",
      price: 24999,
      costPrice: 5000,
      sku: "TGX-API-B2B-001",
      images: [
        { url: "/TagX Pro.png", publicId: "tagx-api", alt: "TagX API dashboard", isPrimary: true },
      ],
      category: "enterprise",
      tags: ["enterprise", "api", "integration", "saas", "b2b"],
      features: ["REST + WebSocket API", "50,000 API calls/month", "Real-time location streams", "Webhook event notifications", "API key management console", "Dedicated integration engineer"],
      specs: { battery: "N/A", range: "N/A", waterproof: "N/A", weight: "N/A", dimensions: "N/A", connectivity: "HTTPS / WSS" },
      isFeatured: false,
      seo: { metaTitle: "TagX Asset Tracking API – Annual Plan | TagX", metaDescription: "TagX Asset Tracking API provides REST + WebSocket access to real-time location data for custom integrations.", keywords: ["tracking api", "asset api", "location api", "enterprise integration"] },
    },
    {
      name: "TagX Retail Inventory Kit (20-pack)",
      slug: "tagx-retail-inventory-kit",
      description: "Twenty TagX Mini units in a locking charging case with retail inventory software. Scan items in/out, track stock movement, and get low-inventory alerts. Designed for small to medium retail stores.",
      shortDescription: "20× Mini tags + inventory software.",
      price: 34999,
      compareAtPrice: 39980,
      costPrice: 18000,
      sku: "TGX-RETAIL-B2B-020",
      images: [
        { url: "/TagX Mini.png", publicId: "tagx-retail-kit", alt: "TagX Retail Inventory Kit", isPrimary: true },
      ],
      category: "enterprise",
      tags: ["enterprise", "retail", "inventory", "warehouse", "b2b"],
      features: ["20× TagX Mini (₹1,749/unit)", "Locking charging case", "Inventory scan in/out", "Low-stock alerts", "POS integration via API", "1-year retail warranty"],
      specs: { battery: "6 months each (CR1220)", range: "60m (197ft)", waterproof: "IP54", weight: "6g each", dimensions: "Each: 40 × 25 × 6 mm", connectivity: "Bluetooth 5.2" },
      isFeatured: false,
      seo: { metaTitle: "TagX Retail Inventory Kit – 20-Pack | TagX", metaDescription: "TagX Retail Inventory Kit includes 20 Mini tags with inventory software for small to medium retail stores.", keywords: ["retail inventory", "stock tracker", "inventory management", "retail tracker"] },
    },
  ]);

  // ── 3. Tracking Devices ──
  console.log("📡 Creating tracking devices...");
  const devices = await TrackingDevice.insertMany([
    {
      user: demo._id,
      name: "TagX Pro",
      type: "tag",
      serialNumber: "TGX-PRO-001A",
      status: "active",
      batteryLevel: 82,
      signalStrength: 75,
      lastSeen: new Date(Date.now() - 2 * 60 * 1000),
      firmwareVersion: "2.4.1",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PRO-2024",
      temperature: 28,
      pairedAt: new Date("2025-12-01"),
      location: {
        lat: 19.0756,
        lng: 72.8777,
        address: "Phoenix Marketcity, Kurla, Mumbai",
        accuracy: 5,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 100,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: true,
      },
      metadata: { source: "retail", purchaseDate: new Date("2025-12-05") },
    },
    {
      user: demo._id,
      name: "iPhone 15",
      type: "phone",
      serialNumber: "TGX-PHN-002B",
      status: "active",
      batteryLevel: 34,
      signalStrength: 90,
      lastSeen: new Date(),
      firmwareVersion: "2.4.0",
      hardwareVersion: "1.1.0",
      manufacturer: "Apple",
      deviceModel: "iPhone 15 Pro",
      temperature: 32,
      pairedAt: new Date("2025-11-15"),
      location: {
        lat: 19.0588,
        lng: 72.8403,
        address: "Home, Bandra West, Mumbai",
        accuracy: 3,
      },
      settings: {
        notifyOnLeftBehind: false,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 50,
        trackingInterval: 120,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Wallet Tag",
      type: "wallet",
      serialNumber: "TGX-WAL-003C",
      status: "idle",
      batteryLevel: 67,
      signalStrength: 45,
      lastSeen: new Date(Date.now() - 1 * 60 * 60 * 1000),
      firmwareVersion: "2.3.2",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-MINI-2024",
      temperature: 26,
      pairedAt: new Date("2026-01-10"),
      location: {
        lat: 19.0756,
        lng: 72.8777,
        address: "Phoenix Marketcity, Kurla, Mumbai",
        accuracy: 10,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 50,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Max (Pet)",
      type: "pet",
      serialNumber: "TGX-PET-004D",
      status: "offline",
      batteryLevel: 8,
      signalStrength: 0,
      lastSeen: new Date(Date.now() - 3 * 60 * 60 * 1000),
      firmwareVersion: "2.4.1",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PET-2024",
      temperature: 30,
      pairedAt: new Date("2026-02-20"),
      location: { lat: 0, lng: 0, address: "Unknown", accuracy: 0 },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 200,
        trackingInterval: 30,
        precisionFindingEnabled: false,
        ledIndicator: true,
      },
      metadata: { petName: "Max", species: "dog", breed: "Golden Retriever" },
    },
    {
      user: demo._id,
      name: "Car Keys",
      type: "key",
      serialNumber: "TGX-KEY-005E",
      status: "active",
      batteryLevel: 91,
      signalStrength: 80,
      lastSeen: new Date(Date.now() - 10 * 60 * 1000),
      firmwareVersion: "2.4.0",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-MINI-2024",
      temperature: 27,
      pairedAt: new Date("2026-03-01"),
      location: {
        lat: 19.0588,
        lng: 72.8403,
        address: "Home, Bandra West, Mumbai",
        accuracy: 2,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 30,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: true,
      },
      metadata: { vehicleType: "car", vehicleModel: "Honda City" },
    },
    {
      user: demo._id,
      name: "Sony Headphones",
      type: "tag",
      serialNumber: "TGX-TAG-006F",
      status: "idle",
      batteryLevel: 45,
      signalStrength: 30,
      lastSeen: new Date(Date.now() - 2 * 60 * 60 * 1000),
      firmwareVersion: "2.3.0",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PRO-2024",
      temperature: 24,
      pairedAt: new Date("2026-01-20"),
      location: {
        lat: 19.1197,
        lng: 72.8464,
        address: "Andheri Metro Station, Mumbai",
        accuracy: 8,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: false,
        geofenceRadius: 50,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Office Bag",
      type: "wallet",
      serialNumber: "TGX-BAG-007G",
      status: "active",
      batteryLevel: 73,
      signalStrength: 65,
      lastSeen: new Date(Date.now() - 30 * 60 * 1000),
      firmwareVersion: "2.4.1",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PRO-2024",
      temperature: 26,
      pairedAt: new Date("2026-01-05"),
      location: {
        lat: 19.076,
        lng: 72.8777,
        address: "BKC, Mumbai",
        accuracy: 6,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 100,
        trackingInterval: 60,
        precisionFindingEnabled: true,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Scooty",
      type: "key",
      serialNumber: "TGX-VHL-008H",
      status: "active",
      batteryLevel: 88,
      signalStrength: 95,
      lastSeen: new Date(Date.now() - 5 * 60 * 1000),
      firmwareVersion: "2.4.0",
      hardwareVersion: "1.1.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-VHL-2024",
      temperature: 35,
      pairedAt: new Date("2026-03-15"),
      location: {
        lat: 19.0588,
        lng: 72.8403,
        address: "Home Parking, Bandra West, Mumbai",
        accuracy: 2,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 20,
        trackingInterval: 120,
        precisionFindingEnabled: false,
        ledIndicator: true,
      },
      metadata: { vehicleType: "scooter", vehicleModel: "TVS Jupiter" },
    },
    {
      user: demo._id,
      name: "Luggage Bag",
      type: "wallet",
      serialNumber: "TGX-LUG-009I",
      status: "offline",
      batteryLevel: 15,
      signalStrength: 0,
      lastSeen: new Date(Date.now() - 24 * 60 * 60 * 1000),
      firmwareVersion: "2.2.1",
      hardwareVersion: "1.0.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-LUG-2024",
      temperature: 22,
      pairedAt: new Date("2026-04-01"),
      location: {
        lat: 28.6139,
        lng: 77.209,
        address: "New Delhi Railway Station",
        accuracy: 50,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 500,
        trackingInterval: 300,
        precisionFindingEnabled: false,
        ledIndicator: false,
      },
      metadata: {},
    },
    {
      user: demo._id,
      name: "Rover (Pet)",
      type: "pet",
      serialNumber: "TGX-PET-010J",
      status: "low_battery",
      batteryLevel: 12,
      signalStrength: 55,
      lastSeen: new Date(Date.now() - 45 * 60 * 1000),
      firmwareVersion: "2.3.3",
      hardwareVersion: "1.2.0",
      manufacturer: "TagX Inc.",
      deviceModel: "TX-PET-2024",
      temperature: 29,
      pairedAt: new Date("2026-04-10"),
      location: {
        lat: 18.9430,
        lng: 72.8225,
        address: "Marine Drive, Mumbai",
        accuracy: 7,
      },
      settings: {
        notifyOnLeftBehind: true,
        notifyOnLowBattery: true,
        notifyOnDisconnect: true,
        geofenceRadius: 200,
        trackingInterval: 30,
        precisionFindingEnabled: false,
        ledIndicator: true,
      },
      metadata: { petName: "Rover", species: "dog", breed: "Labrador" },
    },
  ]);

  // ── 4. Tracking Events ──
  console.log("📋 Creating tracking events...");
  const now = Date.now();
  await TrackingEvent.insertMany([
    {
      device: devices[0]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "TagX Pro spotted at Phoenix Marketcity, Kurla",
      icon: "map-pin",
      source: "bluetooth",
      location: { lat: 19.0756, lng: 72.8777, address: "Phoenix Marketcity, Kurla, Mumbai" },
      metadata: {},
      timestamp: new Date(now - 2 * 60 * 1000),
    },
    {
      device: devices[1]._id,
      type: "connection",
      severity: "info",
      title: "Reconnected",
      description: "iPhone reconnected after being out of range for 12 minutes",
      icon: "bluetooth",
      source: "bluetooth",
      metadata: {},
      timestamp: new Date(now - 5 * 60 * 1000),
    },
    {
      device: devices[3]._id,
      type: "alert",
      severity: "warning",
      title: "Geofence Alert",
      description: "Max left Home zone — last seen at Marine Drive",
      icon: "alert",
      source: "gps",
      location: { lat: 18.943, lng: 72.8225, address: "Marine Drive, Mumbai" },
      metadata: { petName: "Max" },
      timestamp: new Date(now - 20 * 60 * 1000),
    },
    {
      device: devices[0]._id,
      type: "status",
      severity: "info",
      title: "Firmware Updated",
      description: "TagX Pro updated to v2.4.1 successfully",
      icon: "power",
      source: "system",
      metadata: { previousVersion: "2.4.0", newVersion: "2.4.1" },
      timestamp: new Date(now - 2 * 60 * 60 * 1000),
    },
    {
      device: devices[4]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "Car Keys detected at Home parking spot",
      icon: "map-pin",
      source: "bluetooth",
      location: { lat: 19.0588, lng: 72.8403, address: "Home, Bandra West, Mumbai" },
      metadata: {},
      timestamp: new Date(now - 10 * 60 * 1000),
    },
    {
      device: devices[2]._id,
      type: "alert",
      severity: "warning",
      title: "Left Behind Alert",
      description: "Wallet Tag detected as left behind at Phoenix Marketcity",
      icon: "alert",
      source: "bluetooth",
      location: { lat: 19.0756, lng: 72.8777, address: "Phoenix Marketcity, Kurla, Mumbai" },
      metadata: {},
      timestamp: new Date(now - 1 * 60 * 60 * 1000),
    },
    {
      device: devices[5]._id,
      type: "connection",
      severity: "info",
      title: "Disconnected",
      description: "Sony Headphones went out of range at Andheri Metro",
      icon: "wifi",
      source: "bluetooth",
      location: { lat: 19.1197, lng: 72.8464, address: "Andheri Metro, Mumbai" },
      metadata: {},
      timestamp: new Date(now - 2 * 60 * 60 * 1000),
    },
    {
      device: devices[7]._id,
      type: "status",
      severity: "warning",
      title: "Battery Low",
      description: "Scooty tag battery at 12% — consider replacing soon",
      icon: "power",
      source: "system",
      metadata: { batteryLevel: 12 },
      timestamp: new Date(now - 30 * 60 * 1000),
    },
    {
      device: devices[9]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "Rover is roaming at Marine Drive, 500m from home",
      icon: "map-pin",
      source: "gps",
      location: { lat: 18.943, lng: 72.8225, address: "Marine Drive, Mumbai" },
      metadata: {},
      timestamp: new Date(now - 45 * 60 * 1000),
    },
    {
      device: devices[8]._id,
      type: "alert",
      severity: "critical",
      title: "Out of Range",
      description: "Luggage bag tag not seen since yesterday — last pinged at New Delhi Railway Station",
      icon: "alert",
      source: "crowd",
      location: { lat: 28.6139, lng: 77.209, address: "New Delhi Railway Station" },
      metadata: { hoursSinceLastSeen: 24 },
      timestamp: new Date(now - 24 * 60 * 60 * 1000),
    },
    {
      device: devices[6]._id,
      type: "location",
      severity: "info",
      title: "Location Updated",
      description: "Office Bag arrived at BKC, Mumbai",
      icon: "map-pin",
      source: "crowd",
      location: { lat: 19.076, lng: 72.8777, address: "BKC, Mumbai" },
      metadata: {},
      timestamp: new Date(now - 30 * 60 * 1000),
    },
  ]);

  // ── 5. Device Health ──
  console.log("❤️  Creating device health records...");
  await DeviceHealth.insertMany([
    { device: devices[0]._id, uptime: 99.8, signalStrength: 75, batteryHealth: 92, temperature: 28, connectionErrors: 0, firmwareVersion: "2.4.1", timestamp: new Date(now - 10 * 60 * 1000), metrics: [] },
    { device: devices[1]._id, uptime: 98.5, signalStrength: 90, batteryHealth: 78, temperature: 32, memoryUsage: 45, connectionErrors: 2, firmwareVersion: "2.4.0", timestamp: new Date(now - 5 * 60 * 1000), metrics: [] },
    { device: devices[2]._id, uptime: 95.2, signalStrength: 45, batteryHealth: 85, temperature: 26, connectionErrors: 1, firmwareVersion: "2.3.2", timestamp: new Date(now - 1 * 60 * 60 * 1000), metrics: [] },
    { device: devices[3]._id, uptime: 88.0, signalStrength: 0, batteryHealth: 22, temperature: 30, connectionErrors: 15, firmwareVersion: "2.4.1", timestamp: new Date(now - 3 * 60 * 60 * 1000), metrics: [] },
    { device: devices[4]._id, uptime: 99.9, signalStrength: 80, batteryHealth: 97, temperature: 27, connectionErrors: 0, firmwareVersion: "2.4.0", timestamp: new Date(now - 10 * 60 * 1000), metrics: [] },
    { device: devices[5]._id, uptime: 92.1, signalStrength: 30, batteryHealth: 65, temperature: 24, connectionErrors: 3, firmwareVersion: "2.3.0", timestamp: new Date(now - 2 * 60 * 60 * 1000), metrics: [] },
    { device: devices[6]._id, uptime: 97.4, signalStrength: 65, batteryHealth: 88, temperature: 26, connectionErrors: 1, firmwareVersion: "2.4.1", timestamp: new Date(now - 30 * 60 * 1000), metrics: [] },
    { device: devices[7]._id, uptime: 99.6, signalStrength: 95, batteryHealth: 94, temperature: 35, connectionErrors: 0, firmwareVersion: "2.4.0", timestamp: new Date(now - 5 * 60 * 1000), metrics: [] },
    { device: devices[8]._id, uptime: 76.3, signalStrength: 0, batteryHealth: 30, temperature: 22, connectionErrors: 22, firmwareVersion: "2.2.1", timestamp: new Date(now - 24 * 60 * 60 * 1000), metrics: [] },
    { device: devices[9]._id, uptime: 85.0, signalStrength: 55, batteryHealth: 40, temperature: 29, connectionErrors: 5, firmwareVersion: "2.3.3", timestamp: new Date(now - 45 * 60 * 1000), metrics: [] },
    { device: devices[0]._id, uptime: 99.7, signalStrength: 72, batteryHealth: 91, temperature: 27, connectionErrors: 0, firmwareVersion: "2.4.1", timestamp: new Date(now - 2 * 60 * 60 * 1000), metrics: [] },
    { device: devices[1]._id, uptime: 98.5, signalStrength: 88, batteryHealth: 77, temperature: 31, memoryUsage: 48, connectionErrors: 1, firmwareVersion: "2.4.0", timestamp: new Date(now - 1 * 60 * 60 * 1000), metrics: [] },
  ]);

  // ── 6. Privacy Alerts ──
  console.log("🛡️  Creating privacy alerts...");
  const alertSpecs = [
    { severity: "info" as const, title: "Privacy Scan Complete", prompt: "Write a 1-sentence confirmation that no unknown trackers were detected nearby.", fallback: "No unknown trackers detected in your vicinity. Your area is secure." },
    { severity: "warning" as const, title: "Unknown Tracker Detected", prompt: "Write a 1-sentence warning about an unknown Bluetooth device following someone on MG Road for 15 minutes.", fallback: "An unknown Bluetooth device has been following your route for 15 minutes on MG Road." },
    { severity: "critical" as const, title: "Anti-Stalking Alert", prompt: "Write a 1-sentence critical alert about a tracker consistently near someone for over 30 minutes in Indiranagar.", fallback: "A tracker not in your network has been consistently near you for 30+ minutes at Indiranagar." },
    { severity: "info" as const, title: "Safe Zone Verified", prompt: "Write a 1-sentence confirmation that a home zone is secure with no unknown devices in 24 hours.", fallback: "Your Home zone is secure. No unknown devices detected in the last 24 hours." },
    { severity: "warning" as const, title: "AirTag Detected Nearby", prompt: "Write a 1-sentence warning that an Apple AirTag is moving with someone on Commercial Street.", fallback: "An Apple AirTag is moving with you. It may be attached to your belongings." },
    { severity: "info" as const, title: "Scan Complete — All Clear", prompt: "Write a 1-sentence privacy scan result: 12 known devices, 0 unknown.", fallback: "Privacy scan completed. 12 known devices, 0 unknown devices detected." },
    { severity: "critical" as const, title: "Tracker Found in Bag", prompt: "Write a 1-sentence critical alert about an unknown tracker detected near someone for over 1 hour at Orion Mall.", fallback: "An unknown tracking device was detected in your vicinity for over 1 hour at Orion Mall." },
    { severity: "info" as const, title: "Weekly Privacy Report", prompt: "Write a 1-sentence weekly privacy report: 7 scans, 2 unknown trackers resolved.", fallback: "7 scans completed this week. 2 unknown trackers detected and resolved." },
  ];
  const alertDescriptions = await batchGenerate(alertSpecs.map((s) => ({ prompt: s.prompt, fallback: s.fallback })));
  await PrivacyAlert.insertMany([
    { user: demo._id, severity: alertSpecs[0].severity, title: alertSpecs[0].title, description: alertDescriptions[0], metadata: { scanDuration: "2.3s" }, timestamp: new Date(now - 10 * 60 * 1000) },
    { user: demo._id, severity: alertSpecs[1].severity, title: alertSpecs[1].title, description: alertDescriptions[1], location: "Linking Road, Bandra, Mumbai", coordinates: { lat: 19.0588, lng: 72.8403 }, actionLabel: "Investigate", metadata: { deviceType: "BLE", signalStrength: -65 }, timestamp: new Date(now - 30 * 60 * 1000) },
    { user: demo._id, severity: alertSpecs[2].severity, title: alertSpecs[2].title, description: alertDescriptions[2], location: "Bandra West, Mumbai", coordinates: { lat: 19.0588, lng: 72.8403 }, actionLabel: "Scan Now", metadata: { proximityDuration: "32m", detections: 8 }, timestamp: new Date(now - 45 * 60 * 1000) },
    { user: demo._id, severity: alertSpecs[4].severity, title: alertSpecs[4].title, description: alertDescriptions[4], location: "Linking Road, Bandra, Mumbai", coordinates: { lat: 19.0588, lng: 72.8403 }, actionLabel: "Find Device", metadata: { detectedVia: "iOS", manufacturer: "Apple" }, timestamp: new Date(now - 3 * 60 * 60 * 1000) },
    { user: demo._id, severity: alertSpecs[6].severity, title: alertSpecs[6].title, description: alertDescriptions[6], location: "Phoenix Marketcity, Kurla, Mumbai", coordinates: { lat: 19.0756, lng: 72.8777 }, actionLabel: "Locate Device", metadata: { proximityDuration: "67m", detections: 15 }, timestamp: new Date(now - 12 * 60 * 60 * 1000) },
    { user: demo._id, severity: alertSpecs[7].severity, title: alertSpecs[7].title, description: alertDescriptions[7], metadata: { totalScans: 7, threatsFound: 2, threatsResolved: 2 }, timestamp: new Date(now - 24 * 60 * 60 * 1000) },
  ]);

  // ── 7. Notifications ──
  console.log("🔔 Creating notifications...");
  const notifSpecs = [
    { type: "location" as const, priority: "high" as const, title: "TagX Pro Found", prompt: "Write a 1-sentence notification that a tracker was located at Orion Mall within a safe zone.", fallback: "Located at Orion Mall, Sector 3 — within your safe zone." },
    { type: "security" as const, priority: "normal" as const, title: "New Device Paired", prompt: "Write a 1-sentence notification that AirPods Pro were added to a tracker network with encryption.", fallback: "AirPods Pro added to your network. Encryption enabled." },
    { type: "insight" as const, priority: "low" as const, title: "Weekly Report Ready", prompt: "Write a 1-sentence insight that someone saved 23 minutes this week using a tracker.", fallback: "You saved 23 minutes this week by not searching for lost items." },
    { type: "reminder" as const, priority: "normal" as const, title: "Battery Reminder", prompt: "Write a 1-sentence reminder that a wallet tag battery is below 20% and needs replacing.", fallback: "Wallet Tag battery is below 20%. Consider replacing the battery soon." },
    { type: "location" as const, priority: "low" as const, title: "Car Keys Located", prompt: "Write a 1-sentence notification that car keys were found at the home parking spot.", fallback: "Your Car Keys are at Home parking spot." },
    { type: "security" as const, priority: "normal" as const, title: "Privacy Scan Reminder", prompt: "Write a 1-sentence reminder to run a daily privacy scan.", fallback: "You haven't run a privacy scan today. Stay safe!" },
    { type: "insight" as const, priority: "low" as const, title: "Pattern Detected", prompt: "Write a 1-sentence insight about someone leaving their keys in the living room between 6-8 PM.", fallback: "You tend to leave your keys in the living room between 6-8 PM." },
    { type: "reminder" as const, priority: "low" as const, title: "Firmware Update Available", prompt: "Write a 1-sentence notification about new firmware v2.5.0 available for a pet tracker.", fallback: "New firmware v2.5.0 available for TagX Pet." },
    { type: "location" as const, priority: "high" as const, title: "Geofence Alert", prompt: "Write a 1-sentence alert that a pet tracker has left the home safe zone.", fallback: "TagX Pet Rover has left the Home safe zone." },
    { type: "insight" as const, priority: "low" as const, title: "Battery Forecast", prompt: "Write a 1-sentence forecast that a pet tracker battery will last 12 more days.", fallback: "TagX Pet battery predicted to last 12 more days at current usage." },
  ];
  const notifDescriptions = await batchGenerate(notifSpecs.map((s) => ({ prompt: s.prompt, fallback: s.fallback })));
  await Notification.insertMany([
    { user: demo._id, type: notifSpecs[0].type, priority: notifSpecs[0].priority, title: notifSpecs[0].title, description: notifDescriptions[0], actionable: true, category: "device_location", metadata: { deviceId: devices[0]._id.toString() }, timestamp: new Date(now - 2 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[1].type, priority: notifSpecs[1].priority, title: notifSpecs[1].title, description: notifDescriptions[1], read: true, readAt: new Date(now - 14 * 60 * 1000), category: "device_pairing", metadata: {}, timestamp: new Date(now - 15 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[2].type, priority: notifSpecs[2].priority, title: notifSpecs[2].title, description: notifDescriptions[2], read: true, readAt: new Date(now - 55 * 60 * 1000), category: "weekly_report", metadata: { timeSaved: 23, unit: "minutes" }, timestamp: new Date(now - 1 * 60 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[3].type, priority: notifSpecs[3].priority, title: notifSpecs[3].title, description: notifDescriptions[3], actionable: true, actionLabel: "Order Battery", category: "battery", metadata: { deviceId: devices[2]._id.toString(), batteryLevel: 15 }, timestamp: new Date(now - 3 * 60 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[4].type, priority: notifSpecs[4].priority, title: notifSpecs[4].title, description: notifDescriptions[4], read: true, readAt: new Date(now - 8 * 60 * 1000), category: "device_location", metadata: { deviceId: devices[4]._id.toString() }, timestamp: new Date(now - 10 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[5].type, priority: notifSpecs[5].priority, title: notifSpecs[5].title, description: notifDescriptions[5], actionable: true, actionLabel: "Scan Now", category: "privacy", metadata: {}, timestamp: new Date(now - 5 * 60 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[6].type, priority: notifSpecs[6].priority, title: notifSpecs[6].title, description: notifDescriptions[6], category: "behavior", metadata: {}, timestamp: new Date(now - 6 * 60 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[7].type, priority: notifSpecs[7].priority, title: notifSpecs[7].title, description: notifDescriptions[7], actionable: true, actionLabel: "Update Now", actionUrl: "app://firmware", category: "firmware", metadata: { deviceId: devices[3]._id.toString(), version: "2.5.0" }, timestamp: new Date(now - 12 * 60 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[8].type, priority: notifSpecs[8].priority, title: notifSpecs[8].title, description: notifDescriptions[8], actionable: true, category: "geofence", metadata: { deviceId: devices[9]._id.toString(), zone: "Home" }, timestamp: new Date(now - 45 * 60 * 1000) },
    { user: demo._id, type: notifSpecs[9].type, priority: notifSpecs[9].priority, title: notifSpecs[9].title, description: notifDescriptions[9], category: "battery", metadata: { deviceId: devices[3]._id.toString(), daysRemaining: 12 }, timestamp: new Date(now - 2 * 60 * 60 * 1000) },
  ]);

  // ── 8. AI Insights ──
  console.log("🤖 Creating AI insights...");
  const insightSpecs = [
    { type: "insight" as const, category: "usage" as const, title: "Pattern Detected", prompt: "Write a 1-sentence insight about someone who tends to leave their keys in the living room between 6-8 PM.", fallback: "You tend to leave your keys in the living room between 6-8 PM. Check the couch.", conf: 0.87 },
    { type: "prediction" as const, category: "battery" as const, title: "Battery Forecast", prompt: "Write a 1-sentence prediction about a pet tracker battery lasting 12 more days.", fallback: "TagX Pet battery predicted to last 12 more days based on current usage patterns.", conf: 0.94 },
    { type: "alert" as const, category: "location" as const, title: "Unusual Activity", prompt: "Write a 1-sentence alert about a wallet tag moving outside its usual zone during work hours.", fallback: "Wallet Tag moved outside your usual zone during work hours. Possible misplacement.", conf: null },
    { type: "suggestion" as const, category: "general" as const, title: "Optimize Placement", prompt: "Write a 1-sentence suggestion that moving a Bluetooth tracker closer to an entrance improves signal by 40%.", fallback: "Moving your TagX Pro closer to the entrance improves signal strength by 40%.", conf: 0.78 },
    { type: "prediction" as const, category: "usage" as const, title: "Forgetting Pattern", prompt: "Write a 1-sentence prediction about someone having an 82% chance of forgetting their wallet on Friday evenings.", fallback: "Based on your history, there's an 82% chance you'll forget your wallet on Friday evenings.", conf: 0.82 },
    { type: "insight" as const, category: "usage" as const, title: "Recovery Stats", prompt: "Write a 1-sentence insight about someone saving 47 minutes this week using a tracker.", fallback: "You've saved 47 minutes this week using TagX — that's 34% faster than last week.", conf: 0.95 },
    { type: "suggestion" as const, category: "security" as const, title: "Family Sharing Suggestion", prompt: "Write a 1-sentence suggestion to add family members to get notified when they enter safe zones.", fallback: "Add family members to your network to get notified when they enter safe zones.", conf: 0.72 },
    { type: "alert" as const, category: "location" as const, title: "Signal Degradation", prompt: "Write a 1-sentence alert about a Bluetooth tracker signal weakening due to interference.", fallback: "Your TagX Pro signal has been weakening. Check for Bluetooth interference.", conf: null },
    { type: "prediction" as const, category: "usage" as const, title: "Travel Prediction", prompt: "Write a 1-sentence reminder about someone who typically packs their luggage tag on Friday mornings for a trip.", fallback: "You usually pack your Luggage Tag on Friday mornings. Don't forget it for your trip!", conf: 0.88 },
    { type: "insight" as const, category: "usage" as const, title: "Most Used Feature", prompt: "Write a 1-sentence insight about someone using location tracking 73% more than other features.", fallback: "You use location tracking 73% more than any other feature. Precision Finding is your favorite.", conf: 0.91 },
    { type: "alert" as const, category: "location" as const, title: "Max Location Outdated", prompt: "Write a 1-sentence alert about a pet tracker not reporting location for 3 hours, last seen at a park.", fallback: "TagX Pet Max hasn't reported location in 3 hours. Last seen at Cubbon Park.", conf: null },
  ];
  const insightDescriptions = await batchGenerate(insightSpecs.map((s) => ({ prompt: s.prompt, fallback: s.fallback })));
  await AIInsight.insertMany(insightSpecs.map((s, i) => ({
    user: demo._id,
    type: s.type,
    category: s.category,
    title: s.title,
    description: insightDescriptions[i],
    confidence: s.conf ?? undefined,
    actionable: s.type === "alert" || s.type === "suggestion" || s.title === "Pattern Detected" || s.title === "Forgetting Pattern" || s.title === "Travel Prediction" || s.title === "Max Location Outdated",
    modelName: "groq/llama-3.3-70b",
    metadata: {},
    timestamp: new Date(now - [5, 60, 30, 120, 240, 480, 720, 1080, 1440, 2880, 180][i] * 60 * 1000),
  })));

  // ── 9. Family Members ──
  console.log("👨‍👩‍👧‍👦 Creating family members...");
  await FamilyMember.insertMany([
    {
      owner: demo._id,
      user: demo._id,
      name: "Rahul Kapoor",
      email: "demo@tagx.com",
      role: "Owner",
      relationship: "self",
      devices: 10,
      status: "active",
      location: "Home, Bandra West, Mumbai",
      isOwner: true,
      permissions: ["track_location", "view_devices", "receive_alerts", "manage_members", "view_insights"],
      joinedAt: new Date("2025-12-01"),
    },
    {
      owner: demo._id,
      name: "Priya Kapoor",
      email: "priya.kapoor@email.com",
      phone: "+91-9876543210",
      role: "Partner",
      relationship: "wife",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
      devices: 2,
      status: "active",
      location: "Work, MG Road",
      permissions: ["track_location", "view_devices", "receive_alerts", "view_insights"],
      invitedAt: new Date("2026-01-15"),
      joinedAt: new Date("2026-01-20"),
    },
    {
      owner: demo._id,
      name: "Arjun Kapoor",
      email: "arjun.k@school.edu",
      role: "Child",
      relationship: "son",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun",
      devices: 1,
      status: "active",
      location: "School, Indiranagar",
      permissions: ["track_location", "receive_alerts"],
      invitedAt: new Date("2026-02-01"),
      joinedAt: new Date("2026-02-05"),
    },
    {
      owner: demo._id,
      name: "Mr. Kapoor",
      email: "raj.kapoor@email.com",
      role: "Parent",
      relationship: "father",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MrKapoor",
      devices: 3,
      status: "idle",
      location: "Home, Delhi",
      permissions: ["view_devices", "receive_alerts"],
      invitedAt: new Date("2026-03-01"),
    },
    {
      owner: demo._id,
      name: "Mrs. Kapoor",
      email: "sarita.kapoor@email.com",
      role: "Parent",
      relationship: "mother",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=MrsKapoor",
      devices: 2,
      status: "offline",
      location: "Unknown",
      permissions: ["view_devices"],
      invitedAt: new Date("2026-03-01"),
    },
    {
      owner: demo._id,
      name: "Neha Kapoor",
      email: "neha.k@college.edu",
      role: "Sibling",
      relationship: "sister",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Neha",
      devices: 1,
      status: "active",
      location: "College, Koramangala",
      permissions: ["track_location", "view_devices", "receive_alerts"],
      invitedAt: new Date("2026-04-01"),
      joinedAt: new Date("2026-04-05"),
    },
  ]);

  console.log("\n✅ Seed complete!");
  console.log(`   👤 ${2} users (admin + demo)`);
  console.log(`   🏷️  ${products.length} products (${7} B2C + ${products.length - 7} B2B)`);
  console.log(`   📡 ${devices.length} tracking devices`);
  console.log(`   📋 ${11} tracking events`);
  console.log(`   ❤️  ${12} device health records`);
  console.log(`   🛡️  ${8} privacy alerts`);
  console.log(`   🔔 ${10} notifications`);
  console.log(`   🤖 ${11} AI insights`);
  console.log(`   👨‍👩‍👧‍👦 ${6} family members\n`);

  console.log("   Demo login:  demo@tagx.com / Demo@123");
  console.log("   Admin login: admin@tagx.com / Admin@123\n");

  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
